### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by sawtdakhili** [fearlessgeekmedia/wifi4rofi#2]
Issue Description:
When launching wifi4wofi it works but he following error messages are displayed in the terminal:

```
wifi4wofi scan: no process found
/usr/bin/wifi4wofi: line 31: 35207 Killed yad --title="wifi4wofi scan" --text="Scanning for networks" --no-buttons width=300 height=200 --undecorated --splash --fixed --center --skip-taskbar

(wofi:35297): Gtk-CRITICAL **: 11:56:38.109: gtk_widget_set_size_request: assertion 'height >= -1' failed
Error: unknown connection ''
```

Steps to Reproduce:
1. Launch wifi4wofi through the terminal.
2. Observe the error messages mentioned above.

Additional Information:
- Arch Linux OS
- The issue occurs consistently and persists after updating the system.
- Attempts to remove and reinstall the application have been unsuccessful.

Please let me know if you need any further information. Thank you.

**Comment by fearlessgeekmedia** [comment]
It's normal. It has always done the same thing for me, even with the code I forked it from. It's basically a non-issue, but I definitely understand the concern. 

FYI, you'll find a lot of programs and scripts will have similar error messages. I get these kinds of errors when running a web browser from the command line, for example.

**Comment by fearlessgeekmedia** [comment]
I'll go ahead and mark this as closed, as ultimately it's a non-issue.
